;METADATA=(Diff=true, UseCommands=true)
[ScalabilityGroups]
sg.ViewDistanceQuality=3
sg.AntiAliasingQuality=2
sg.ShadowQuality=2
sg.GlobalIlluminationQuality=2
sg.ReflectionQuality=2
sg.PostProcessQuality=2
sg.TextureQuality=2
sg.EffectsQuality=2
sg.FoliageQuality=3
sg.ShadingQuality=2
sg.LandscapeQuality=3
sg.CloudsQuality=3
sg.ResolutionQuality=0

[/Script/Subnautica2.SN2SettingsLocal]
DesiredUserChosenDeviceProfileSuffix=
ROGAllyCustomModeEnabled=0
FrameRateLimit_OnBattery=60.000000
FrameRateLimit_InMenu=60.000000
FrameRateLimit_WhenBackgrounded=30.000000
UpscalingMethod=U_TSR
TSRQualityMode=3
DLSSQualityMode=-1
DynamicResFrameTime=16.666666
UpscalingFrameGeneration=0
ResolutionScaleFixed=0.800000
ResolutionScaleDLSS=0.800000
ResolutionScaleMin=0.500000
ResolutionScaleMax=1.000000
bUseHeadphoneMode=False
AudioOutputDeviceId=
GammaValue=2.400000
EnableMotionBlur=Off
EnableChromaticAberration=Off
EnableLensFlare=Off
EnableUnderwaterBlur=Off
bUseVSync=False
bUseDynamicResolution=True
ResolutionSizeX=3840
ResolutionSizeY=2160
LastUserConfirmedResolutionSizeX=3840
LastUserConfirmedResolutionSizeY=2160
FullscreenMode=1
LastConfirmedFullscreenMode=1
PreferredFullscreenMode=1
Version=5
AudioQualityLevel=0
LastConfirmedAudioQualityLevel=0
FrameRateLimit=120.000000
DesiredScreenWidth=3072
DesiredScreenHeight=1728
LastUserConfirmedDesiredScreenWidth=3072
LastUserConfirmedDesiredScreenHeight=1728
LastRecommendedScreenWidth=-1.000000
LastRecommendedScreenHeight=-1.000000
LastCPUBenchmarkResult=189.430786
LastGPUBenchmarkResult=1447.674805
LastGPUBenchmarkMultiplier=1.000000
bUseHDRDisplayOutput=False
HDRDisplayOutputNits=1000
LastCPUBenchmarkSteps=210.404022
LastCPUBenchmarkSteps=175.448608
LastGPUBenchmarkSteps=1810.627319
LastGPUBenchmarkSteps=1275.799316
LastGPUBenchmarkSteps=2248.870605
LastGPUBenchmarkSteps=959.391113
LastGPUBenchmarkSteps=295.884705
LastGPUBenchmarkSteps=979.539917
LastGPUBenchmarkSteps=3186.963379

[/Script/Engine.GameUserSettings]
bUseDesiredScreenHeight=False

[UWE.PersistentInfo]
InstallGUID=00014D7108DEB91F1853D11B02CD4E8D
RunNumber=14
ReadNewsVersion=lgp7e89tmtdvsxgv87622vea

